[package]
name = "select-statement-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quickcheck = "1"
quickcheck_macros = "1"
postgres = "0.19"
rand = "0.8"